- name: laptop
  hosts:
    - localhost
  tasks:
    - copy:
        src: xremap.service
        dest: ~/.config/systemd/user/
    - command: systemctl --user daemon-reload
    - command: systemctl --user enable xremap.service
    - command: systemctl --user start xremap.service
    # xremap + udev
    - copy:
        src: bin/systemctl-as-gnome-user
        dest: /usr/local/bin
      become: true
    - copy:
        src: keyboard.rules
        dest: /etc/udev/rules.d/
      become: true
    # Atlassian keep-alive
    - copy:
        src: atlassian-keepalive.service
        dest: ~/.config/systemd/user/
      tags: atlassian
    - copy:
        src: atlassian-keepalive.timer
        dest: ~/.config/systemd/user/
      tags: atlassian
    - command: systemctl --user daemon-reload
      tags: atlassian
    - command: systemctl --user enable atlassian-keepalive.timer
      tags: atlassian
    - command: systemctl --user start atlassian-keepalive.timer
      tags: atlassian
