# See Also:
# https://mutelight.org/practical-tmux
# http://d.hatena.ne.jp/naoya/20130108/1357630895

# Emacs
bind-key C-y paste-buffer

## The default prefix key is C-b, but I use that for backward-char.
set-option -g prefix C-z

## Use C-f, C-b, ... in copy-mode
set-window-option -g mode-keys emacs

## C-x 2, C-x 3 and other shortcuts for split-window
bind -Tctrl_x 2 split-window -v
bind -Tctrl_x 3 split-window -h
bind -Tctrl_x Any { send C-x; send }
bind -Troot C-x switch-client -Tctrl_x

# Like Screen
bind-key C-a last-window

# Start numbering at 1, because 0 is too far
set -g base-index 1

# Color
set -g status-bg gray
set -g status-fg black
set-window-option -g window-status-current-style fg=white,bg=blue

# Don't have to show anything around the status bar
set -g status-left ''
set -g status-right ''

# Remove the delay
set -g escape-time 0

# Pane Title
setw -g window-status-current-format "#{window_index}:#{pane_title}#{window_flags} "
setw -g window-status-format         "#{window_index}:#{pane_title}#{window_flags} "

# Mouse
set-option -g mouse on

# Make 80x24 work
# https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it
set-option -g allow-passthrough on

set -g set-titles on
set -g set-titles-string "#T @ #H"

# Plugins

# ## tmux-fingers
# https://github.com/Morantron/tmux-fingers/
# https://secon.dev/entry/2026/01/09/210000/
set -g @fingers-pattern-0 '^[a-z0-9]([-a-z0-9]{8,}[a-z0-9])'
run-shell ~/.tmux/plugins/tmux-fingers/tmux-fingers.tmux

# Platform-dependent settings

## Wayland
if-shell -b '[ ! -z "$WAYLAND_DISPLAY" ]' {
    # Need to call wl-copy due to https://gitlab.gnome.org/GNOME/vte/-/issues/2495
    set -g copy-command 'wl-copy'
}

## macOS
if-shell -b '[ "$(uname)" = Darwin ]' {
    set-option -g default-command "reattach-to-user-namespace -l /bin/zsh"
    set -g copy-command 'pbcopy'
}


