- name: laptop
  hosts: localhost
  handlers:
    - name: reload systemd
      systemd_service:
        daemon_reload: true
        scope: user
  tasks:
    # files/home mirrors the paths it installs to
    - copy:
        src: home/
        dest: ~/
        mode: preserve
      notify: reload systemd
      tags: always
    - meta: flush_handlers
    - systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
        scope: user
      loop:
        - xremap.service
        - atlassian-keepalive.timer
