all: moccur-edit.el sgml-match-mode.el auto-install.el

sgml-match-mode.el:
	curl -LO https://github.com/kzys/sgml-match-mode/raw/master/lisp/sgml-match-mode.el

moccur-edit.el:
	curl -O http://www.bookshelf.jp/elc/moccur-edit.el

js.el:

	curl -O http://repo.or.cz/w/emacs.git/blob_plain/6b45354a9e8f5db5e283025cc0b7ea053408f176:/lisp/progmodes/js.el

auto-install.el:
	curl -LO http://www.emacswiki.org/emacs/download/auto-install.el
